import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/provider/AuthProvider";
import { LoginLink, LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";
import {getKindeServerSession} from "@kinde-oss/kinde-auth-nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { isAuthenticated } = getKindeServerSession();
  const isUserAuthenticated = await isAuthenticated();

  return (<AuthProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-2 py-5">
          <nav className="flex justify-between items-center max-w-screen-xl mx-auto">
            <Link href="/" className="font-semibold text-lg sm:text-2xl text-cyan-400">Assignment</Link>

            <ul className="flex justify-end gap-2 sm:gap-3">
              <li>
                <Link href="/">Home</Link>
              </li>
              {isUserAuthenticated ? <>
                <li>
                  <Link href="/profile">Profile</Link>
                </li>

                <li>
                  <LogoutLink>Logout</LogoutLink>
                </li>
              </> : <li>
                <LoginLink postLoginRedirectURL="/">Login</LoginLink>
              </li>}


            </ul>
          </nav>
        </header>

        <main className="px-2 py-10">
          {children}
        </main>
      </body>
    </html>
  </AuthProvider>);
}
